//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Definitions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Definitions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Definitions", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Page.
        /// </summary>
        internal static string Calendar_Title {
            get {
                return ResourceManager.GetString("Calendar.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect.
        /// </summary>
        internal static string Redirect_Title {
            get {
                return ResourceManager.GetString("Redirect.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of registrations.
        /// </summary>
        internal static string RegistrationContainer_Description {
            get {
                return ResourceManager.GetString("RegistrationContainer.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration list.
        /// </summary>
        internal static string RegistrationContainer_Title {
            get {
                return ResourceManager.GetString("RegistrationContainer.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A registration page.
        /// </summary>
        internal static string RegistrationPage_Description {
            get {
                return ResourceManager.GetString("RegistrationPage.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string RegistrationPage_Title {
            get {
                return ResourceManager.GetString("RegistrationPage.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A registration form.
        /// </summary>
        internal static string Registration_Description {
            get {
                return ResourceManager.GetString("Registration.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string Registration_Title {
            get {
                return ResourceManager.GetString("Registration.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select user.
        /// </summary>
        internal static string SelectUser_Title {
            get {
                return ResourceManager.GetString("SelectUser.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Map.
        /// </summary>
        internal static string SiteMap_Title {
            get {
                return ResourceManager.GetString("SiteMap.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain Content Page.
        /// </summary>
        internal static string TextPage_Title {
            get {
                return ResourceManager.GetString("TextPage.Title", resourceCulture);
            }
        }
    }
}
