//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Editables {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Editables() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Editables", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string AcceptationStatus_Title {
            get {
                return ResourceManager.GetString("AcceptationStatus.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string advanced_TabText {
            get {
                return ResourceManager.GetString("advanced.TabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any pictures taken of this person may be used in publications from KVG.
        /// </summary>
        internal static string AllowPictures_CheckBoxText {
            get {
                return ResourceManager.GetString("AllowPictures.CheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture allowance.
        /// </summary>
        internal static string AllowPictures_Title {
            get {
                return ResourceManager.GetString("AllowPictures.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attn.
        /// </summary>
        internal static string Attn_Title {
            get {
                return ResourceManager.GetString("Attn.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        internal static string DateOfBirth_Title {
            get {
                return ResourceManager.GetString("DateOfBirth.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eats no eggs.
        /// </summary>
        internal static string EatsNoEggs_CheckBoxText {
            get {
                return ResourceManager.GetString("EatsNoEggs.CheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eats no fish.
        /// </summary>
        internal static string EatsNoFish_CheckBoxText {
            get {
                return ResourceManager.GetString("EatsNoFish.CheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eats no meat.
        /// </summary>
        internal static string EatsNoMeat_CheckBoxText {
            get {
                return ResourceManager.GetString("EatsNoMeat.CheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eats no.
        /// </summary>
        internal static string EatsNo_Title {
            get {
                return ResourceManager.GetString("EatsNo.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einddatum.
        /// </summary>
        internal static string EndDate_Title {
            get {
                return ResourceManager.GetString("EndDate.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string FirstName_Title {
            get {
                return ResourceManager.GetString("FirstName.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer Text.
        /// </summary>
        internal static string FooterText_Title {
            get {
                return ResourceManager.GetString("FooterText.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handicapped?.
        /// </summary>
        internal static string HandicapFlag_Title {
            get {
                return ResourceManager.GetString("HandicapFlag.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday.
        /// </summary>
        internal static string Holiday_Title {
            get {
                return ResourceManager.GetString("Holiday.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used in multiple sites scenarios to determine which start page match a certain domain name (e.g. n2cms.com).
        /// </summary>
        internal static string HostName_HelpTitle {
            get {
                return ResourceManager.GetString("HostName.HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Name.
        /// </summary>
        internal static string HostName_Title {
            get {
                return ResourceManager.GetString("HostName.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Card number.
        /// </summary>
        internal static string IdNumber_Title {
            get {
                return ResourceManager.GetString("IdNumber.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images (one image url on each line).
        /// </summary>
        internal static string Images_Title {
            get {
                return ResourceManager.GetString("Images.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displayed above the main text.
        /// </summary>
        internal static string Image_HelpTitle {
            get {
                return ResourceManager.GetString("Image.HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main image.
        /// </summary>
        internal static string Image_Title {
            get {
                return ResourceManager.GetString("Image.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQ.
        /// </summary>
        internal static string IQ_Title {
            get {
                return ResourceManager.GetString("IQ.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is member of KVG?.
        /// </summary>
        internal static string IsKvgMember_Title {
            get {
                return ResourceManager.GetString("IsKvgMember.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KVG Membership number.
        /// </summary>
        internal static string KvgMembership_Title {
            get {
                return ResourceManager.GetString("KvgMembership.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string LastName_Title {
            get {
                return ResourceManager.GetString("LastName.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest changes max count.
        /// </summary>
        internal static string LatestChangesMaxCount_Title {
            get {
                return ResourceManager.GetString("LatestChangesMaxCount.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Layout.
        /// </summary>
        internal static string Layout_Title {
            get {
                return ResourceManager.GetString("Layout.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked text.
        /// </summary>
        internal static string LinkText_Title {
            get {
                return ResourceManager.GetString("LinkText.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link url.
        /// </summary>
        internal static string LinkUrl_Title {
            get {
                return ResourceManager.GetString("LinkUrl.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location_Title {
            get {
                return ResourceManager.GetString("Location.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MedicalRecordOk_CheckBoxText {
            get {
                return ResourceManager.GetString("MedicalRecordOk.CheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Record Ok.
        /// </summary>
        internal static string MedicalRecordOk_Title {
            get {
                return ResourceManager.GetString("MedicalRecordOk.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mental handicap.
        /// </summary>
        internal static string MentalHandicap_Title {
            get {
                return ResourceManager.GetString("MentalHandicap.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivation of acceptation / rejection.
        /// </summary>
        internal static string Motivation_Title {
            get {
                return ResourceManager.GetString("Motivation.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displayed in the browser&apos;s address bar..
        /// </summary>
        internal static string Name_HelpTitle {
            get {
                return ResourceManager.GetString("Name.HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL segment.
        /// </summary>
        internal static string Name_Title {
            get {
                return ResourceManager.GetString("Name.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string Number_Title {
            get {
                return ResourceManager.GetString("Number.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other utilities.
        /// </summary>
        internal static string OtherUtilities_Title {
            get {
                return ResourceManager.GetString("OtherUtilities.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string Owner_Title {
            get {
                return ResourceManager.GetString("Owner.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brings own wheelchair.
        /// </summary>
        internal static string OwnWheelChair_Title {
            get {
                return ResourceManager.GetString("OwnWheelChair.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Paid_CheckBoxText {
            get {
                return ResourceManager.GetString("Paid.CheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid?.
        /// </summary>
        internal static string Paid_Title {
            get {
                return ResourceManager.GetString("Paid.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comes as:.
        /// </summary>
        internal static string Participation_Title {
            get {
                return ResourceManager.GetString("Participation.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string PaymentInfo_Title {
            get {
                return ResourceManager.GetString("PaymentInfo.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string PhoneNumber_Title {
            get {
                return ResourceManager.GetString("PhoneNumber.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical handicap.
        /// </summary>
        internal static string PhysicalHandicap_Title {
            get {
                return ResourceManager.GetString("PhysicalHandicap.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of birth.
        /// </summary>
        internal static string PlaceOfBirth_Title {
            get {
                return ResourceManager.GetString("PlaceOfBirth.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code.
        /// </summary>
        internal static string PostalCode_Title {
            get {
                return ResourceManager.GetString("PostalCode.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and .
        /// </summary>
        internal static string Published_BetweenText {
            get {
                return ResourceManager.GetString("Published.BetweenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published between.
        /// </summary>
        internal static string Published_CheckBoxText {
            get {
                return ResourceManager.GetString("Published.CheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page is available to visitors between these dates. An empty start date means the item isn&apos;t published yet. An empty stop date means the item never expires..
        /// </summary>
        internal static string Published_HelpTitle {
            get {
                return ResourceManager.GetString("Published.HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect to.
        /// </summary>
        internal static string RedirectUrl_Title {
            get {
                return ResourceManager.GetString("RedirectUrl.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a holiday.
        /// </summary>
        internal static string SelectHoliday_Title {
            get {
                return ResourceManager.GetString("SelectHoliday.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display title above text content.
        /// </summary>
        internal static string ShowTitle_CheckBoxText {
            get {
                return ResourceManager.GetString("ShowTitle.CheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unchecking this options hides the page title.
        /// </summary>
        internal static string ShowTitle_HelpTitle {
            get {
                return ResourceManager.GetString("ShowTitle.HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show title on page.
        /// </summary>
        internal static string ShowTitle_Title {
            get {
                return ResourceManager.GetString("ShowTitle.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        internal static string SmtpHost_Title {
            get {
                return ResourceManager.GetString("SmtpHost.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string SmtpPassword {
            get {
                return ResourceManager.GetString("SmtpPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string SmtpPort_Title {
            get {
                return ResourceManager.GetString("SmtpPort.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string SmtpUser_Title {
            get {
                return ResourceManager.GetString("SmtpUser.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social handicap.
        /// </summary>
        internal static string SocialHandicap_Title {
            get {
                return ResourceManager.GetString("SocialHandicap.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begindatum.
        /// </summary>
        internal static string StartDate_Title {
            get {
                return ResourceManager.GetString("StartDate.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string Street_Title {
            get {
                return ResourceManager.GetString("Street.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address suffix.
        /// </summary>
        internal static string Suffix_Title {
            get {
                return ResourceManager.GetString("Suffix.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default text on this page, displayed in the central column..
        /// </summary>
        internal static string Text_HelpTitle {
            get {
                return ResourceManager.GetString("Text.HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main text.
        /// </summary>
        internal static string Text_Title {
            get {
                return ResourceManager.GetString("Text.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Theme.
        /// </summary>
        internal static string Theme_Title {
            get {
                return ResourceManager.GetString("Theme.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displyed as the page&apos;s main header and in menus..
        /// </summary>
        internal static string Title_HelpTitle {
            get {
                return ResourceManager.GetString("Title.HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title_Title {
            get {
                return ResourceManager.GetString("Title.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is a vegetarian?.
        /// </summary>
        internal static string Vegetarian_Title {
            get {
                return ResourceManager.GetString("Vegetarian.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reveal page in navigation.
        /// </summary>
        internal static string Visible_CheckBoxText {
            get {
                return ResourceManager.GetString("Visible.CheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unchecking this options hides the page in menus but it&apos;s still available if you know the address to it..
        /// </summary>
        internal static string Visible_HelpTitle {
            get {
                return ResourceManager.GetString("Visible.HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visble in menu&apos;s.
        /// </summary>
        internal static string Visible_Title {
            get {
                return ResourceManager.GetString("Visible.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit planned / Visted.
        /// </summary>
        internal static string VisitDate_Title {
            get {
                return ResourceManager.GetString("VisitDate.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit report.
        /// </summary>
        internal static string VisitReport_Title {
            get {
                return ResourceManager.GetString("VisitReport.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visually impaired?.
        /// </summary>
        internal static string VisuallyImpaired_Title {
            get {
                return ResourceManager.GetString("VisuallyImpaired.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs a wheelchair?.
        /// </summary>
        internal static string WheelChair_Title {
            get {
                return ResourceManager.GetString("WheelChair.Title", resourceCulture);
            }
        }
    }
}
