//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EditableContainers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditableContainers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.EditableContainers", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted?.
        /// </summary>
        internal static string acceptationFieldSet_Legend {
            get {
                return ResourceManager.GetString("acceptationFieldSet.Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string advanced_TabText {
            get {
                return ResourceManager.GetString("advanced.TabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact persons.
        /// </summary>
        internal static string contactsTab_TabText {
            get {
                return ResourceManager.GetString("contactsTab.TabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string content_TabText {
            get {
                return ResourceManager.GetString("content.TabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended page properties.
        /// </summary>
        internal static string details_Legend {
            get {
                return ResourceManager.GetString("details.Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diet.
        /// </summary>
        internal static string dietFieldSet_Legend {
            get {
                return ResourceManager.GetString("dietFieldSet.Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handicap.
        /// </summary>
        internal static string handicapFieldSet_Legend {
            get {
                return ResourceManager.GetString("handicapFieldSet.Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical data (contd).
        /// </summary>
        internal static string medicalDetailsTab_TabText {
            get {
                return ResourceManager.GetString("medicalDetailsTab.TabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical data.
        /// </summary>
        internal static string medicalSummaryTab_TabText {
            get {
                return ResourceManager.GetString("medicalSummaryTab.TabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string mobileFieldSet_Legend {
            get {
                return ResourceManager.GetString("mobileFieldSet.Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More information.
        /// </summary>
        internal static string moreInfoTab_TabText {
            get {
                return ResourceManager.GetString("moreInfoTab.TabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal data.
        /// </summary>
        internal static string personalDataTab_TabText {
            get {
                return ResourceManager.GetString("personalDataTab.TabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal data.
        /// </summary>
        internal static string personalDetailsFieldSet_Legend {
            get {
                return ResourceManager.GetString("personalDetailsFieldSet.Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string registrationDetailsFieldSet_Legend {
            get {
                return ResourceManager.GetString("registrationDetailsFieldSet.Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string registrationPanel_TabText {
            get {
                return ResourceManager.GetString("registrationPanel.TabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEO.
        /// </summary>
        internal static string seo_TabText {
            get {
                return ResourceManager.GetString("seo.TabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP settings.
        /// </summary>
        internal static string smtp_TabText {
            get {
                return ResourceManager.GetString("smtp.TabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string telephoneFieldSet_Legend {
            get {
                return ResourceManager.GetString("telephoneFieldSet.Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheelchair.
        /// </summary>
        internal static string wheelChairFieldSet_Legend {
            get {
                return ResourceManager.GetString("wheelChairFieldSet.Legend", resourceCulture);
            }
        }
    }
}
